CREATE TABLE bills
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT                                  NOT NULL,
    price    DECIMAL(*, 2)                           NOT NULL,
    date     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bills PRIMARY KEY (id)
);

CREATE TABLE boxes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    open_time   TIME WITHOUT TIME ZONE DEFAULT '10:00',
    close_time  TIME WITHOUT TIME ZONE DEFAULT '22:00',
    coefficient DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_boxes PRIMARY KEY (id)
);

CREATE TABLE offers
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    duration BIGINT                                  NOT NULL,
    price    DECIMAL(*, 2)                           NOT NULL,
    CONSTRAINT pk_offers PRIMARY KEY (id)
);

CREATE TABLE operators
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    min_discount INTEGER,
    max_discount INTEGER,
    box_id       BIGINT,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_operators PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    offer_id BIGINT                                  NOT NULL,
    status   VARCHAR(255),
    date     TIMESTAMP WITHOUT TIME ZONE,
    duration BIGINT,
    discount INTEGER,
    price    DECIMAL(*, 2)                           NOT NULL,
    box_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    username   VARCHAR(20),
    password   VARCHAR(255),
    role       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE bills
    ADD CONSTRAINT FK_BILLS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE operators
    ADD CONSTRAINT FK_OPERATORS_ON_BOX FOREIGN KEY (box_id) REFERENCES boxes (id);

ALTER TABLE operators
    ADD CONSTRAINT FK_OPERATORS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_BOX FOREIGN KEY (box_id) REFERENCES boxes (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_OFFER FOREIGN KEY (offer_id) REFERENCES offers (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);